USE master
DROP DATABASE QLSANPHAM
CREATE DATABASE QLSANPHAM;
USE QLSANPHAM;

CREATE TABLE LOAISP (
    MALOAI CHAR(2) PRIMARY KEY,
    TENLOAI NVARCHAR(30)
);

CREATE TABLE SANPHAM (
    MASP CHAR(6) PRIMARY KEY,
    TENSP NVARCHAR(30),
    NGAYNHAP DATETIME,
    MALOAI CHAR(2),
    FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI)
);

INSERT INTO LOAISP (MALOAI, TENLOAI)
VALUES
('L1', N'ĐIỆN TỬ'),
('L2', N'GIA DỤNG'),
('L3', N'VĂN PHÒNG PHẨM');

INSERT INTO SANPHAM (MASP, TENSP, NGAYNHAP, MALOAI)
VALUES
('SP001', N'TIVI SAMSUNG', '2024-01-01', 'L1'),
('SP002', N'TỦ LẠNH TOSHIBA', '2024-01-02', 'L2'),
('SP003', N'BÚT BI THIÊN LONG', '2024-01-03', 'L3');

SELECT * FROM LOAISP;
SELECT * FROM SANPHAM;

